### ISSUE TITLE
Meteor is not a front end framework

### ISSUE THREAD

**Issue by rivertam** [iCHAIT/awesome-subreddits#11]
Meteor is more of a back end framework, but I don't really think it belongs in either category. Not sure where it should go.

**Comment by iCHAIT** [comment]
Maybe we can have a new category? Or we can place it under Miscellaneous..!!

**Comment by rivertam** [comment]
Yeah I definitely don't think it should be in Misc, but I don't know if like "full-stack framework" is a big enough category to actually have as a category.

**Comment by rivertam** [comment]
It could go in JS but nothing else under Programming Languages is a framework, as far as I can see
